# Generated by Django 4.1.5 on 2023-07-12 13:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='+92-3211234567', max_length=128, region=None),
        ),
    ]
