# Generated by Django 4.1.5 on 2023-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_trafficuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficuser',
            old_name='user',
            new_name='user_ip',
        ),
    ]
