services:
  app:
    build: .
    volumes:
      - .:/src
    image: app:src
    container_name: HRE_Web
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - SECRET_KEY="dxkw4*re8@pc8rv68$%v75$$hhx3wmn2s@_h&5-9=zmd4zej*="