# Generated by Django 4.1.5 on 2023-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('', 'Category'), ('Homes', (('house', 'House <span class="bedicon"><ion-icon name="home-outline"></ion-icon></span>'), ('flat', 'Flat'), ('up', 'Upper Portion'), ('lp', 'Lower Portion'), ('fh', 'Farm House'), ('room', 'Room'), ('ph', 'Penthouse'))), ('Plots', (('rp', 'Residential Plots'), ('cp', 'Commercial Plots'), ('al', 'Agricultural Land'), ('il', 'Industrial Land'), ('pfile', 'Plot File'), ('pform', 'Plot Form'))), ('Commercial', (('off', 'Office'), ('shop', 'Shop'), ('wh', 'Warehouse'), ('fact', 'Factory'), ('buil', 'Building'))), ('other', 'Other')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('S', 'For Sale'), ('R', 'For Rent')], default='S', max_length=2),
        ),
    ]
