# Generated by Django 4.1.5 on 2023-07-15 11:02

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=listing.models.ListingImage.user_directory_path),
        ),
    ]
