# Generated by Django 4.1.5 on 2023-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
