# Generated by Django 4.1.5 on 2023-07-18 08:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=124, unique=True, verbose_name='Feature Name')),
            ],
        ),
        migrations.CreateModel(
            name='AmenityRelatedToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ListingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='custom_bathroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='custom_bedroom',
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='(Un)Mark as sold'),
        ),
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Listing Specification Value (maximum of 255 characters)', max_length=255, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listing.listingspecification')),
            ],
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='listing.amenityrelatedtocategory')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='listing.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required and unique', max_length=124, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category Safe URL')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='listing.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='amenityrelatedtocategory',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='listing.category'),
        ),
        migrations.AddField(
            model_name='amenityrelatedtocategory',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.amenities'),
        ),
    ]
