# Generated by Django 4.1.5 on 2023-07-18 08:16

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_amenities_amenityrelatedtocategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecificationValue',
            new_name='ListingSpecificationValue',
        ),
        migrations.RenameField(
            model_name='listingspecificationvalue',
            old_name='product',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=mptt.fields.TreeForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listing.category'),
            preserve_default=False,
        ),
    ]
