# Generated by Django 4.1.5 on 2023-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_listing_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenities',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.RemoveField(
            model_name='amenityrelatedtocategory',
            name='feature',
        ),
        migrations.AddField(
            model_name='amenityrelatedtocategory',
            name='feature',
            field=models.ManyToManyField(to='listing.amenities'),
        ),
    ]
