# Generated by Django 4.1.5 on 2023-07-18 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_amenities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity', to='listing.amenities'),
        ),
        migrations.DeleteModel(
            name='AmenityRelatedToCategory',
        ),
    ]
