# Generated by Django 4.1.5 on 2023-07-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_listingamenity_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='purpose',
        ),
    ]
