# Generated by Django 4.1.5 on 2023-07-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_alter_listingspecificationvalue_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon',
            field=models.CharField(blank=True, max_length=124, null=True, verbose_name='Feature Icon'),
        ),
    ]
