# Generated by Django 4.1.3 on 2023-03-16 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=24)),
                ('lname', models.CharField(blank=True, max_length=24)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Website')),
                ('bio_info', models.CharField(max_length=500)),
                ('estate_name', models.TextField(default='Haris Real Estate', max_length=256)),
                ('profile_image', models.ImageField(blank=True, upload_to=website.models.Profile.user_directory_path)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('purpose', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent Out')], default='S', max_length=2)),
                ('category', models.CharField(choices=[('Homes', (('house', 'House'), ('flat', 'Flat'), ('up', 'Upper Portion'), ('lp', 'Lower Portion'), ('fh', 'Farm House'), ('room', 'Room'), ('ph', 'Penthouse'))), ('Plots', (('rp', 'Residential Plots'), ('cp', 'Commercial Plots'), ('al', 'Agricultural Land'), ('il', 'Industrial Land'), ('pfile', 'Plot File'), ('pform', 'Plot Form'))), ('Commercial', (('off', 'Office'), ('shop', 'Shop'), ('wh', 'Warehouse'), ('fact', 'Factory'), ('buil', 'Building'))), ('other', 'Other')], default='', max_length=5)),
                ('bedroom', models.CharField(blank=True, choices=[('S', 'Studio'), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=6, null=True)),
                ('bathroom', models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], max_length=1, null=True)),
                ('area_size', models.IntegerField()),
                ('area_size_unit', models.CharField(choices=[('SFt', 'Sq. Ft.'), ('SM', 'Sq. M.'), ('SYd', 'Sq. Yd.'), ('M', 'Marla'), ('K', 'Kanal')], default='M', max_length=10)),
                ('city', models.CharField(choices=[('lhr', 'Lahore'), ('khi', 'Karachi'), ('isl', 'Islamabad')], default='lhr', max_length=3)),
                ('address', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=600)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to=website.models.Images.user_directory_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='website.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=24)),
                ('lname', models.CharField(max_length=24)),
                ('comment', models.TextField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.listing')),
            ],
        ),
    ]
