# Generated by Django 4.1.3 on 2022-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio_info',
            field=models.TextField(default='hello', max_length=500),
            preserve_default=False,
        ),
    ]
