# Generated by Django 4.1.3 on 2023-02-13 12:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+92-3115239286', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
