# Generated by Django 4.1.3 on 2023-01-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Homes', (('house', 'House'), ('', 'Flat'), ('', 'Upper Portion'), ('', 'Lower Portion'), ('', 'Farm House'), ('', 'Room'), ('', 'Penthouse'))), ('Plots', (('rp', 'Residential Plots'), ('', 'Commercial Plots'), ('', 'Agricultural Land'), ('', 'Industrial Land'), ('', 'Plot File'), ('', 'Plot Form'))), ('Commercial', (('off', 'Office'), ('', 'Shop'), ('', 'Warehouse'), ('', 'Factory'), ('', 'Building'), ('', 'Other')))], default='house', max_length=5),
        ),
    ]
