# Generated by Django 4.1.3 on 2023-01-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Homes', (('house', 'House'),)), ('Plots', (('rp', 'Residential Plots'),)), ('Commercial', (('off', 'Office'),)), ('other', 'Other')], default='', max_length=5),
        ),
    ]
