# Generated by Django 4.1.3 on 2022-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='purpose',
            field=models.CharField(choices=[('S', 'Sale'), ('R', 'Rent Out')], default='S', max_length=2),
        ),
    ]
