# Generated by Django 4.1.3 on 2023-02-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_listing_price_unit_alter_listing_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price_unit',
            new_name='area_size_unit',
        ),
    ]
