# Generated by Django 4.1.3 on 2023-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_price_unit_listing_area_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
