# Generated by Django 4.1.7 on 2023-03-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_profile_url_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
