# Generated by Django 4.1.3 on 2023-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_listing_address_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estate_name',
            field=models.TextField(default='Haris Real Estate', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_info',
            field=models.CharField(max_length=500),
        ),
    ]
