# Generated by Django 4.1.3 on 2022-12-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_listing_city_alter_listing_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area_size',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
