# Generated by Django 4.1.7 on 2023-03-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_comments_comment_rename_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_info',
            field=models.TextField(max_length=1000),
        ),
    ]
