# Generated by Django 4.1.3 on 2023-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_listing_bathroom_listing_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathroom',
            field=models.CharField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedroom',
            field=models.CharField(blank=True, choices=[('S', 'Studio'), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=6, null=True),
        ),
    ]
