# Generated by Django 4.1.7 on 2023-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_listing_description_alter_profile_bio_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_info',
            field=models.TextField(blank=True, help_text='Optional', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='estate_name',
            field=models.CharField(blank=True, help_text='Optional', max_length=256, null=True),
        ),
    ]
