# Generated by Django 4.1.7 on 2023-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_listing_custom_bedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='custom_bathroom',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
