# Generated by Django 4.1.7 on 2023-06-03 13:11

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_listing_category_alter_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=website.models.Image.user_directory_path, validators=[website.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('', 'City'), ('abd', 'Attock'), ('abt', 'Abbottabad'), ('bhr', 'Bahawalnagar'), ('bwn', 'Bhawana'), ('bhk', 'Bhakkar'), ('bwp', 'Bahawalpur'), ('cwp', 'Chishtian'), ('dgh', 'Dera Ghazi Khan'), ('dnb', 'Dinawali'), ('dip', 'Dipalpur'), ('fdr', 'Fateh Jhang'), ('fsl', 'Faisalabad'), ('ghk', 'Gujar Khan'), ('gjr', 'Gujranwala'), ('grk', 'Gwadar'), ('grw', 'Gujranwala'), ('gjr', 'Gujrat'), ('hyd', 'Hyderabad'), ('isl', 'Islamabad'), ('jlm', 'Jalalpur'), ('jwn', 'Jaranwala'), ('jwp', 'Jhelum'), ('khr', 'Khairpur'), ('khi', 'Karachi'), ('khr', 'Khanewal'), ('ktt', 'Kotli'), ('kwb', 'Kot Adu'), ('lai', 'Lalamusa'), ('lhr', 'Lahore'), ('ldr', 'Lodhran'), ('lrd', 'Larkana'), ('ltr', 'Layyah'), ('mll', 'Mian Channu'), ('mlk', 'Malakwal'), ('mlt', 'Mardan'), ('mrd', 'Multan'), ('mnt', 'Mansehra'), ('mgw', 'Mandi Bahauddin'), ('mwm', 'Mianwali'), ('mtr', 'Multan'), ('mzt', 'Murree'), ('mzw', 'Muzaffargarh'), ('ngt', 'Narowal'), ('nwn', 'Nankana Sahib'), ('pwp', 'Peshawar'), ('phl', 'Pattoki'), ('qta', 'Quetta'), ('qrb', 'Quetta Residency'), ('rch', 'Rajanpur'), ('rnw', 'Rawalpindi'), ('rkn', 'Rahim Yar Khan'), ('rwp', 'Rawalpindi'), ('sgr', 'Sargodha'), ('skt', 'Sialkot'), ('shw', 'Sheikhupura'), ('swn', 'Swat'), ('sak', 'Sargodha'), ('sbq', 'Sahiwal'), ('ska', 'Sakrand'), ('skz', 'Sukheki'), ('stw', 'Sialkot'), ('suk', 'Sukkur'), ('swl', 'Sahiwal'), ('sgr', 'Sargodha'), ('swl', 'Sialkot'), ('saw', 'Sawat'), ('ttn', 'Toba Tek Singh'), ('vhn', 'Vehari'), ('wah', 'Wah Cantt'), ('wln', 'Wazirabad')], default='lhr', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=website.models.Profile.user_directory_path, validators=[website.models.validate_image_size]),
        ),
    ]
