# Generated by Django 4.1.7 on 2023-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_image_image_alter_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
